[project]
name = 'clarity'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[project.deployments]
contracts = ["fundraising"]
public_keys = ["ded1ea002d91f566fb1b0e0fa46d3024b8f3513fd67550527d5632636e3f5af401", "ded1ea002d91f566fb1b0e0fa46d3024b8f3513fd67550527d5632636e3f5af401"]
private_keys = ["753b7cc01a1a2e86221266a154af739463fce51219d97e4f856cd7200c3bd2a601", "753b7cc01a1a2e86221266a154af739463fce51219d97e4f856cd7200c3bd2a601"]

[contracts.fundraising]
path = 'contracts/fundraising.clar'
clarity_version = 3
epoch = 3.0
mnemonic = "shift swear blouse shell script mother mask cancel dwarf north animal dawn"
balance = 100_000_000_000
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
